{% set python_min = '3.10' %}
{% set name = "openfe-analysis" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/OpenFreeEnergy/openfe_analysis.git
  git_rev: v{{ version }}
  git_depth: -1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - versioningit
  run:
    - MDAnalysis >=2.8.0
    - click
    - netCDF4
    - openff-units
    - python >={{ python_min }}
    - tqdm
    - pyyaml

test:
  imports:
    - openfe_analysis
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/OpenFreeEnergy/openfe_analysis
  summary: 'Analysis tools for the openfe ecosystem'
  description: |
    openfe-analysis is a set of analysis tools to check the 
    health of free energy calculations in the openfe ecosystem.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/OpenFreeEnergy/openfe_analysis
  dev_url: https://github.com/OpenFreeEnergy/openfe_analysis

extra:
  recipe-maintainers:
    - dwhswenson
    - ialibay
    - mikemhenry
    - atravitz
    - hannahbaumann
